### ISSUE TITLE
Provide a list of available courses for a semester

### ISSUE THREAD

**Issue by sjiang1** [COSC381-2023Fall/course-registration-api#1]
**User story**
As a student who is enrolled for the next semester, I want to see all the courses available for a major selected to register for the next semester.

**Task**

- [x] Make a course class: prefix (major), number, cap, instructor, name, place, meeting times. 
- [x] Create a list of courses
- [x] Create an API method to return the list of courses: inputs should be a major prefix, the output should be a list of all the courses available for the major.

**Acceptance Criteria**

- [x] The API method should return the correct list of courses for any major
