### ISSUE TITLE
Show a student's registered courses

### ISSUE THREAD

**Issue by sjiang1** [COSC381-2023Fall/course-registration-api#2]
**User Story**
As a student who is enrolled for the next semester, I want to see the courses that I have registered for the next semester, so that I know whether I have registered enough credit hours.

**Tasks**

- [ ] Create a Student class: EID, a list of registered courses, name
- [ ] Have a way to add an available course to the registered courses:
    * Add a _method_ in Student class for registering a course.
        * The inputs should be a course prefix and a course number (Assume every course section has a unique "course prefix + course number".
    * The method should check if the prefix + course number is valid or not.
- [ ] Add an API: the input should be the student's EID, the output should be a list of courses

**Acceptance Criteria**
- [ ] Have unit tests for Student class
- [ ] Have unit tests for the API method
- [ ] Make sure you utilize coverage, fixture, mock.
